name: Test Suite

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ruff:
    timeout-minutes: 5
    name: Check format + lint with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ruff lint check
        uses: chartboost/ruff-action@v1
      - name: Ruff format check
        uses: chartboost/ruff-action@v1
        with:
          args: format --check

  pyright:
    timeout-minutes: 5
    name: Check types with pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: "3.11"
      - run: poetry install
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - uses: jakebailey/pyright-action@v2
